
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/CAC 

module CAC(PPI, K, OPO, LPO);
  input [23:0] PPI, K;
  input OPO;
  output LPO;
  wire [23:0] PPI, K;
  wire OPO;
  wire LPO;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73;
  XOR2_X1 g1797(.A (n_73), .B (n_72), .Z (LPO));
  XOR2_X1 g1798(.A (n_71), .B (OPO), .Z (n_73));
  OR2_X1 g1799(.A1 (n_71), .A2 (n_66), .ZN (n_72));
  NOR2_X1 g1800(.A1 (n_70), .A2 (PPI[16]), .ZN (n_71));
  NAND2_X1 g1801(.A1 (n_69), .A2 (PPI[17]), .ZN (n_70));
  NOR3_X1 g1802(.A1 (n_68), .A2 (PPI[18]), .A3 (PPI[20]), .ZN (n_69));
  NAND4_X1 g1803(.A1 (n_67), .A2 (n_10), .A3 (PPI[19]), .A4 (PPI[21]),
       .ZN (n_68));
  NOR4_X1 g1804(.A1 (n_65), .A2 (n_24), .A3 (PPI[1]), .A4 (PPI[23]),
       .ZN (n_67));
  NOR4_X1 g1807(.A1 (n_64), .A2 (n_59), .A3 (n_57), .A4 (n_33), .ZN
       (n_66));
  NAND4_X1 g1805(.A1 (n_63), .A2 (PPI[3]), .A3 (PPI[4]), .A4 (PPI[2]),
       .ZN (n_65));
  NAND4_X1 g1809(.A1 (n_58), .A2 (n_60), .A3 (n_61), .A4 (n_62), .ZN
       (n_64));
  NOR4_X1 g1806(.A1 (n_56), .A2 (n_5), .A3 (PPI[7]), .A4 (PPI[5]), .ZN
       (n_63));
  NOR4_X1 g1811(.A1 (n_55), .A2 (n_36), .A3 (n_13), .A4 (n_9), .ZN
       (n_62));
  NOR4_X1 g1812(.A1 (n_54), .A2 (n_32), .A3 (n_11), .A4 (n_4), .ZN
       (n_61));
  NOR4_X1 g1813(.A1 (n_52), .A2 (n_29), .A3 (n_45), .A4 (n_46), .ZN
       (n_60));
  NAND4_X1 g1814(.A1 (n_50), .A2 (n_27), .A3 (n_19), .A4 (n_25), .ZN
       (n_59));
  NOR4_X1 g1815(.A1 (n_51), .A2 (n_26), .A3 (n_42), .A4 (n_41), .ZN
       (n_58));
  NAND4_X1 g1816(.A1 (n_49), .A2 (n_1), .A3 (n_2), .A4 (n_30), .ZN
       (n_57));
  NAND2_X1 g1808(.A1 (n_53), .A2 (PPI[8]), .ZN (n_56));
  NAND3_X1 g1819(.A1 (n_18), .A2 (n_48), .A3 (n_34), .ZN (n_55));
  NAND3_X1 g1820(.A1 (n_47), .A2 (n_7), .A3 (n_31), .ZN (n_54));
  NOR4_X1 g1810(.A1 (n_14), .A2 (PPI[10]), .A3 (PPI[11]), .A4 (PPI[9]),
       .ZN (n_53));
  NAND3_X1 g1821(.A1 (n_40), .A2 (n_44), .A3 (n_28), .ZN (n_52));
  NAND3_X1 g1822(.A1 (n_21), .A2 (n_23), .A3 (n_37), .ZN (n_51));
  NOR3_X1 g1818(.A1 (n_35), .A2 (n_17), .A3 (n_15), .ZN (n_50));
  NOR2_X1 g1823(.A1 (n_6), .A2 (n_38), .ZN (n_49));
  NAND2_X1 g1851(.A1 (n_12), .A2 (K[17]), .ZN (n_48));
  NAND2_X1 g1852(.A1 (n_3), .A2 (K[21]), .ZN (n_47));
  NOR2_X1 g1853(.A1 (n_39), .A2 (K[8]), .ZN (n_46));
  NOR2_X1 g1854(.A1 (n_43), .A2 (K[9]), .ZN (n_45));
  NAND2_X1 g1855(.A1 (n_43), .A2 (K[9]), .ZN (n_44));
  NOR2_X1 g1856(.A1 (n_22), .A2 (K[13]), .ZN (n_42));
  NOR2_X1 g1857(.A1 (n_20), .A2 (K[14]), .ZN (n_41));
  NAND2_X1 g1858(.A1 (n_39), .A2 (K[8]), .ZN (n_40));
  NOR2_X1 g1859(.A1 (n_0), .A2 (K[5]), .ZN (n_38));
  XNOR2_X1 g1824(.A (PPI[12]), .B (K[12]), .ZN (n_37));
  XOR2_X1 g1825(.A (PPI[19]), .B (K[19]), .Z (n_36));
  XOR2_X1 g1826(.A (PPI[2]), .B (K[2]), .Z (n_35));
  XNOR2_X1 g1827(.A (PPI[18]), .B (K[18]), .ZN (n_34));
  XOR2_X1 g1828(.A (PPI[7]), .B (K[7]), .Z (n_33));
  XOR2_X1 g1829(.A (PPI[23]), .B (K[23]), .Z (n_32));
  XNOR2_X1 g1830(.A (PPI[20]), .B (K[20]), .ZN (n_31));
  XNOR2_X1 g1831(.A (PPI[4]), .B (K[4]), .ZN (n_30));
  XOR2_X1 g1832(.A (PPI[11]), .B (K[11]), .Z (n_29));
  XNOR2_X1 g1833(.A (PPI[10]), .B (K[10]), .ZN (n_28));
  XNOR2_X1 g1834(.A (PPI[3]), .B (K[3]), .ZN (n_27));
  XOR2_X1 g1835(.A (PPI[15]), .B (K[15]), .Z (n_26));
  OR2_X1 g1836(.A1 (n_24), .A2 (K[0]), .ZN (n_25));
  NAND2_X1 g1837(.A1 (n_22), .A2 (K[13]), .ZN (n_23));
  NAND2_X1 g1838(.A1 (n_20), .A2 (K[14]), .ZN (n_21));
  NAND2_X1 g1839(.A1 (n_16), .A2 (PPI[1]), .ZN (n_19));
  NAND2_X1 g1840(.A1 (n_8), .A2 (K[16]), .ZN (n_18));
  NOR2_X1 g1841(.A1 (n_16), .A2 (PPI[1]), .ZN (n_17));
  AND2_X1 g1842(.A1 (n_24), .A2 (K[0]), .ZN (n_15));
  NAND4_X1 g1817(.A1 (PPI[13]), .A2 (PPI[15]), .A3 (PPI[14]), .A4
       (PPI[12]), .ZN (n_14));
  NOR2_X1 g1843(.A1 (n_12), .A2 (K[17]), .ZN (n_13));
  NOR2_X1 g1844(.A1 (n_10), .A2 (K[22]), .ZN (n_11));
  NOR2_X1 g1845(.A1 (n_8), .A2 (K[16]), .ZN (n_9));
  NAND2_X1 g1846(.A1 (n_10), .A2 (K[22]), .ZN (n_7));
  NOR2_X1 g1847(.A1 (n_5), .A2 (K[6]), .ZN (n_6));
  NOR2_X1 g1848(.A1 (n_3), .A2 (K[21]), .ZN (n_4));
  NAND2_X1 g1849(.A1 (n_5), .A2 (K[6]), .ZN (n_2));
  NAND2_X1 g1850(.A1 (n_0), .A2 (K[5]), .ZN (n_1));
  INV_X1 g1860(.A (PPI[6]), .ZN (n_5));
  INV_X1 g1870(.A (PPI[5]), .ZN (n_0));
  INV_X1 g1865(.A (PPI[8]), .ZN (n_39));
  INV_X1 g1868(.A (PPI[13]), .ZN (n_22));
  INV_X1 g1871(.A (PPI[17]), .ZN (n_12));
  INV_X1 g1862(.A (PPI[0]), .ZN (n_24));
  INV_X1 g1869(.A (PPI[14]), .ZN (n_20));
  INV_X1 g1864(.A (PPI[21]), .ZN (n_3));
  INV_X1 g1866(.A (PPI[9]), .ZN (n_43));
  INV_X1 g1867(.A (K[1]), .ZN (n_16));
  INV_X1 g1863(.A (PPI[16]), .ZN (n_8));
  INV_X1 g1861(.A (PPI[22]), .ZN (n_10));
endmodule

