
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/CAC 

module CAC(PPI, K, OPO, LPO);
  input [31:0] PPI, K;
  input OPO;
  output LPO;
  wire [31:0] PPI, K;
  wire OPO;
  wire LPO;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99;
  XOR2_X1 g2636(.A (n_99), .B (n_98), .Z (LPO));
  XNOR2_X1 g2637(.A (n_97), .B (OPO), .ZN (n_99));
  NOR2_X1 g2638(.A1 (n_97), .A2 (n_90), .ZN (n_98));
  NOR4_X1 g2639(.A1 (n_96), .A2 (n_46), .A3 (PPI[18]), .A4 (PPI[16]),
       .ZN (n_97));
  NAND4_X1 g2640(.A1 (n_95), .A2 (PPI[21]), .A3 (PPI[22]), .A4
       (PPI[20]), .ZN (n_96));
  NOR4_X1 g2641(.A1 (n_94), .A2 (PPI[25]), .A3 (PPI[26]), .A4
       (PPI[24]), .ZN (n_95));
  NAND2_X1 g2642(.A1 (n_93), .A2 (PPI[28]), .ZN (n_94));
  NOR3_X1 g2643(.A1 (n_92), .A2 (PPI[29]), .A3 (PPI[30]), .ZN (n_93));
  NAND4_X1 g2644(.A1 (n_91), .A2 (PPI[23]), .A3 (PPI[27]), .A4
       (PPI[19]), .ZN (n_92));
  AND3_X1 g2645(.A1 (n_89), .A2 (PPI[31]), .A3 (PPI[0]), .ZN (n_91));
  NOR4_X1 g2649(.A1 (n_88), .A2 (n_86), .A3 (n_79), .A4 (n_80), .ZN
       (n_90));
  NOR4_X1 g2646(.A1 (n_87), .A2 (n_54), .A3 (PPI[3]), .A4 (PPI[1]), .ZN
       (n_89));
  NAND4_X1 g2650(.A1 (n_81), .A2 (n_82), .A3 (n_83), .A4 (n_84), .ZN
       (n_88));
  NAND4_X1 g2647(.A1 (n_85), .A2 (n_0), .A3 (PPI[6]), .A4 (PPI[4]), .ZN
       (n_87));
  NAND4_X1 g2651(.A1 (n_78), .A2 (n_77), .A3 (n_6), .A4 (n_66), .ZN
       (n_86));
  NOR3_X1 g2648(.A1 (n_76), .A2 (n_1), .A3 (PPI[7]), .ZN (n_85));
  NOR4_X1 g2658(.A1 (n_70), .A2 (n_61), .A3 (n_17), .A4 (n_19), .ZN
       (n_84));
  NOR4_X1 g2653(.A1 (n_75), .A2 (n_10), .A3 (n_56), .A4 (n_57), .ZN
       (n_83));
  NOR4_X1 g2654(.A1 (n_74), .A2 (n_7), .A3 (n_44), .A4 (n_47), .ZN
       (n_82));
  NOR4_X1 g2655(.A1 (n_72), .A2 (n_2), .A3 (n_29), .A4 (n_30), .ZN
       (n_81));
  NAND4_X1 g2656(.A1 (n_73), .A2 (n_64), .A3 (n_31), .A4 (n_49), .ZN
       (n_80));
  NAND4_X1 g2657(.A1 (n_71), .A2 (n_62), .A3 (n_24), .A4 (n_41), .ZN
       (n_79));
  NOR4_X1 g2659(.A1 (n_69), .A2 (n_5), .A3 (n_48), .A4 (n_45), .ZN
       (n_78));
  NOR4_X1 g2660(.A1 (n_68), .A2 (n_3), .A3 (n_60), .A4 (n_37), .ZN
       (n_77));
  NAND4_X1 g2652(.A1 (n_67), .A2 (PPI[10]), .A3 (PPI[11]), .A4
       (PPI[9]), .ZN (n_76));
  NAND3_X1 g2662(.A1 (n_51), .A2 (n_53), .A3 (n_8), .ZN (n_75));
  NAND3_X1 g2663(.A1 (n_38), .A2 (n_40), .A3 (n_4), .ZN (n_74));
  NOR3_X1 g2664(.A1 (n_63), .A2 (n_55), .A3 (n_36), .ZN (n_73));
  NAND3_X1 g2665(.A1 (n_26), .A2 (n_28), .A3 (n_9), .ZN (n_72));
  NOR3_X1 g2666(.A1 (n_11), .A2 (n_21), .A3 (n_33), .ZN (n_71));
  NAND3_X1 g2667(.A1 (n_58), .A2 (n_14), .A3 (n_12), .ZN (n_70));
  NAND2_X1 g2668(.A1 (n_23), .A2 (n_43), .ZN (n_69));
  NAND2_X1 g2669(.A1 (n_34), .A2 (n_16), .ZN (n_68));
  NOR4_X1 g2661(.A1 (n_59), .A2 (n_65), .A3 (PPI[14]), .A4 (PPI[12]),
       .ZN (n_67));
  XOR2_X1 g2678(.A (K[15]), .B (n_65), .Z (n_66));
  XNOR2_X1 g2682(.A (PPI[3]), .B (K[3]), .ZN (n_64));
  XOR2_X1 g2683(.A (PPI[0]), .B (K[0]), .Z (n_63));
  XNOR2_X1 g2684(.A (PPI[7]), .B (K[7]), .ZN (n_62));
  XOR2_X1 g2685(.A (PPI[27]), .B (K[27]), .Z (n_61));
  NOR2_X1 g2686(.A1 (n_59), .A2 (K[13]), .ZN (n_60));
  NAND2_X1 g2687(.A1 (n_18), .A2 (K[25]), .ZN (n_58));
  NOR2_X1 g2688(.A1 (n_50), .A2 (K[30]), .ZN (n_57));
  NOR2_X1 g2689(.A1 (n_52), .A2 (K[28]), .ZN (n_56));
  AND2_X1 g2690(.A1 (n_54), .A2 (K[2]), .ZN (n_55));
  NAND2_X1 g2691(.A1 (n_52), .A2 (K[28]), .ZN (n_53));
  NAND2_X1 g2692(.A1 (n_50), .A2 (K[30]), .ZN (n_51));
  NAND2_X1 g2693(.A1 (n_35), .A2 (PPI[1]), .ZN (n_49));
  NOR2_X1 g2694(.A1 (n_22), .A2 (K[9]), .ZN (n_48));
  NOR2_X1 g2695(.A1 (n_46), .A2 (K[17]), .ZN (n_47));
  NOR2_X1 g2696(.A1 (n_42), .A2 (K[10]), .ZN (n_45));
  NOR2_X1 g2697(.A1 (n_39), .A2 (K[16]), .ZN (n_44));
  NAND2_X1 g2698(.A1 (n_42), .A2 (K[10]), .ZN (n_43));
  NAND2_X1 g2699(.A1 (n_32), .A2 (PPI[4]), .ZN (n_41));
  NAND2_X1 g2700(.A1 (n_39), .A2 (K[16]), .ZN (n_40));
  NAND2_X1 g2701(.A1 (n_46), .A2 (K[17]), .ZN (n_38));
  NOR2_X1 g2702(.A1 (n_15), .A2 (K[14]), .ZN (n_37));
  NOR2_X1 g2703(.A1 (n_35), .A2 (PPI[1]), .ZN (n_36));
  NAND2_X1 g2704(.A1 (n_59), .A2 (K[13]), .ZN (n_34));
  NOR2_X1 g2705(.A1 (n_32), .A2 (PPI[4]), .ZN (n_33));
  OR2_X1 g2706(.A1 (n_54), .A2 (K[2]), .ZN (n_31));
  NOR2_X1 g2707(.A1 (n_25), .A2 (K[21]), .ZN (n_30));
  NOR2_X1 g2708(.A1 (n_27), .A2 (K[22]), .ZN (n_29));
  NAND2_X1 g2709(.A1 (n_27), .A2 (K[22]), .ZN (n_28));
  NAND2_X1 g2710(.A1 (n_25), .A2 (K[21]), .ZN (n_26));
  NAND2_X1 g2711(.A1 (n_20), .A2 (PPI[6]), .ZN (n_24));
  NAND2_X1 g2712(.A1 (n_22), .A2 (K[9]), .ZN (n_23));
  NOR2_X1 g2713(.A1 (n_20), .A2 (PPI[6]), .ZN (n_21));
  NOR2_X1 g2714(.A1 (n_18), .A2 (K[25]), .ZN (n_19));
  NOR2_X1 g2715(.A1 (n_13), .A2 (K[26]), .ZN (n_17));
  NAND2_X1 g2716(.A1 (n_15), .A2 (K[14]), .ZN (n_16));
  NAND2_X1 g2717(.A1 (n_13), .A2 (K[26]), .ZN (n_14));
  XNOR2_X1 g2670(.A (PPI[24]), .B (K[24]), .ZN (n_12));
  XOR2_X1 g2671(.A (PPI[5]), .B (K[5]), .Z (n_11));
  XOR2_X1 g2672(.A (PPI[31]), .B (K[31]), .Z (n_10));
  XNOR2_X1 g2673(.A (PPI[20]), .B (K[20]), .ZN (n_9));
  XNOR2_X1 g2674(.A (PPI[29]), .B (K[29]), .ZN (n_8));
  XOR2_X1 g2675(.A (PPI[19]), .B (K[19]), .Z (n_7));
  XNOR2_X1 g2676(.A (PPI[11]), .B (K[11]), .ZN (n_6));
  XOR2_X1 g2677(.A (PPI[8]), .B (K[8]), .Z (n_5));
  XNOR2_X1 g2679(.A (PPI[18]), .B (K[18]), .ZN (n_4));
  XOR2_X1 g2680(.A (PPI[12]), .B (K[12]), .Z (n_3));
  XOR2_X1 g2681(.A (PPI[23]), .B (K[23]), .Z (n_2));
  INV_X1 g2720(.A (PPI[26]), .ZN (n_13));
  INV_X1 g2722(.A (K[6]), .ZN (n_20));
  INV_X1 g2723(.A (PPI[14]), .ZN (n_15));
  INV_X1 g2719(.A (PPI[9]), .ZN (n_22));
  INV_X1 g2735(.A (PPI[25]), .ZN (n_18));
  INV_X1 g2732(.A (PPI[30]), .ZN (n_50));
  INV_X1 g2725(.A (PPI[28]), .ZN (n_52));
  INV_X1 g2733(.A (K[1]), .ZN (n_35));
  INV_X1 g2727(.A (PPI[22]), .ZN (n_27));
  INV_X1 g2718(.A (PPI[16]), .ZN (n_39));
  INV_X1 g2726(.A (K[4]), .ZN (n_32));
  INV_X1 g2721(.A (PPI[15]), .ZN (n_65));
  INV_X1 g2736(.A (PPI[8]), .ZN (n_1));
  INV_X1 g2730(.A (PPI[13]), .ZN (n_59));
  INV_X1 g2731(.A (PPI[17]), .ZN (n_46));
  INV_X1 g2728(.A (PPI[10]), .ZN (n_42));
  INV_X1 g2734(.A (PPI[5]), .ZN (n_0));
  INV_X1 g2729(.A (PPI[21]), .ZN (n_25));
  INV_X1 g2724(.A (PPI[2]), .ZN (n_54));
endmodule

